### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by SeekingMini** [17665347409/Music-Downloader_TJS#1]
可以公布源代码吗？

**Comment by 17665347409** [comment]
目前并没有开源的准备，但是你可以去查看另一个项目，包括完整的TJS的获取QQ音乐和网易云音乐的组件
https://github.com/messoer/KRKR-QQMusicService

**Comment by 17665347409** [comment]
主界面的代码由于过于混乱而且简单所以并不需要开源，QQ音乐的和网易云音乐的获取组件都是开源的，如果需要的话可以直接调用，目前由于Mess API出事了，所以现在两个API中只有QQ音乐的搜索功能能使用
